# Change these first
owner: jona-facturante # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: Facturante 2 
    url: https://app.facturante.com/iniciar-sesion
  - name: Facturante 2 Test
    url: https://apptest.facturante.com/iniciar-sesion
  - name: Facturante Site
    url: https://www.facturante.com/
  - name: Facturante Base
    url: https://www.facturante.com/Usuarios/LogOn
  - name: Test Broken Site 
    url: https://thissitedoesnotexist.koj.co

assignees: # Users to assign downtime issues (optional)
  - jona-facturante

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /Facturante-Status-App
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Facturante Status APP
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
